// 翻译数据
const translations = {
    zh: {
        nav: {
            home: "首页",
            education: "教育",
            publications: "论文",
            research: "科研",
            projects: "项目",
            competitions: "竞赛",
            skills: "技能",
            honors: "荣誉",
            others: "其他",
            contact: "联系"
        },
        home: {
            name: "李炜仪",
            research: "研究方向：大模型与智能体安全 / 可验证行为与强化学习对齐",
            personalPage: "个人主页"
        },
        footer: {
            lastUpdate: "最后更新"
        },
        modal: {
            selectLanguage: "请选择语言 / Please Select Language"
        },
        education: {
            title: "教育背景",
            university: "北京邮电大学 | 智能科学与技术",
            period: "(2023.09 -- 2027.06)",
            gpa: "GPA: 3.88/4.0 | 加权平均分: 93.44/100",
            rank: "专业排名: 1/98（1.0%）",
            courses: "优势课程"
        },
        publications: {
            title: "论文",
            zhiwujie: {
                title: "智体无界 — 基于类脑架构的运动智能体",
                badge1: "国创赛",
                badge2: "铜奖"
            }
        },
        research: {
            title: "科研经历",
            lab1: {
                name: "江淮前沿技术协同创新中心AI安全专业部",
                period: "(2025.06 -- 至今)",
                position: "本科实习生 | 导师：房江博士",
                project1: {
                    title: "[1] Stylistic Idiosyncrasies of Code Generated by Large Language Models(Accepted by CSCWD)",
                    desc1: "项目描述: 针对大模型生成代码的普及带来审计安全问题，本研究结合监督对比学习与分类微调，通过构建多模型生成的高质量代码问答数据集，实现对不同 LLM 生成代码的精细识别与风格特征提取。实验结果显示模型可区分度显著，达 93.25% 准确率，对代码来源识别与审计具有重要价值。",
                    desc2: "个人贡献：作为<strong>第一作者</strong>，负责多类代码生成数据集构建与清洗；基于 Meta-Llama-3-8B 的 LLM2Vec 构建编码器，完成监督对比学习与 M 类分类器训练；提取并量化代码风格特征，包括变量命名、注释使用等结构化模式，分析模型差异；绘制科研图表并可视化实验结果；完成论文撰写及实验附录整理。"
                },
                project2: {
                    title: "[2] SAT4RIDS: Self-Supervised Learning Adversarial Training Framework for Robust Network Intrusion Detection System（Manuscript prepared）",
                    desc1: "项目描述: 网络入侵检测中的异常流量识别长期面临对抗样本下鲁棒性不足的问题。本研究提出自监督 + 对抗训练结合的网络入侵检测框架，将对抗样本生成融入自监督学习。在CICIoT2022与ISCXVPN2016数据集上性能优异，原始样本准确率达到 99.86%，对抗样本准确率为 87.53%。",
                    desc2: "个人贡献：作为<strong>第一作者</strong>，负责自监督特征学习框架设计，并引入对抗训练机制以提升模型鲁棒性；分析原始与对抗样本的性能差异并量化结果；完成论文撰写并绘制科研图表，呈现模型鲁棒性提升效果。"
                }
            },
            lab2: {
                name: "北京邮电大学网络系统架构与融合重点实验室",
                period: "(2025.11 -- 至今)",
                position: "本科实习生 | 导师：夏海轮教授",
                project1: {
                    title: "[1] Signal-SGN++: Topology-Enhanced Time–Frequency Spiking Graph Network for Skeleton-Based Action Recognition(IEEE TNNLS, Under Review)",
                    desc1: "项目描述: 针对资源受限设备下骨骼动作识别的精度与能耗问题，本研究结合 1D 脉冲图卷积与频率脉冲卷积，同时建模骨骼关节的空间拓扑、时间动态和频域特征。基于 NTU-RGB+D/NTU120/NW-UCLA 数据集验证，Top-1 精度较基线提升 8-15%，能耗较传统 GCN 下降 30%，FLOPs 降低 77%-93%。",
                    desc2: "个人贡献：参与 MWTF 模块（多尺度小波变换融合）和 TSSA 模块（拓扑转换自注意力机制）的技术设计与实现；负责科研图表绘制与方法可视化，将复杂网络结构、实验流程及结果直观呈现。"
                }
            },
            lab3: {
                name: "北京邮电大学网络空间安全学院 – 移动互联网安全技术国家工程实验室",
                period: "(2024.06 -- 至今)",
                position: "本科实习生 | 导师：南国顺教授",
                project1: {
                    title: "[1] When Contrastive Decoding Teaches Time: Annotation-Free RL for Reasoning over Temporal Dynamics（TPAMI, Under Review）",
                    desc1: "项目描述：针对多模态大模型在视频时序建模中因果逻辑不一致及人工构建标注信号成本高的问题，本项目提出基于对比解码 + GRPO 强化学习的框架，在正序与反序视频中增强因果信号，实现动态视频任务的因果一致性与时序敏感性提升，方法在无标注情况下达到 SOTA 性能。",
                    desc2: "个人贡献：负责文献调研与综述，系统梳理视频时序建模前沿方法与技术路线；收集、清洗并整合多源视频数据集（RTime-QA、TempCompass、MVBench、TemporalQA）；开发不同模型推理脚本（VideoLLaVA-7B、MiniCPM-V-2.6-8B、TimeChat）及 GPT-3 评测脚本。代码可通过 <a href=\"https://anonymous.4open.science/r/test-G15b7423-117/README.md\" target=\"_blank\">此链接</a> 获取。"
                }
            },
            lab4: {
                name: "中国科学院自动化研究所 · 复杂系统认知与决策重点实验室",
                period: "(2026.01 -- 至今)",
                position: "本科实习生 | 导师：黄凯奇教授",
                direction: "研究方向：大语言模型驱动的人机博弈代理（LLM-based Agents for Human-Machine Gaming）",
                mainWork: "主要工作与成果：",
                work1: {
                    title: "自演化博弈代理机制研究",
                    item1Html: "基于大语言模型构建自演化代理框架（参考 <a href=\"https://proceedings.neurips.cc/paper_files/paper/2024/hash/df2d62b96a4003203450cf89cd338bb7-Abstract-Conference.html\" target=\"_blank\">Richelieu</a>）。",
                    item2: "研究自对弈（Self-Play）方法，让代理在无需人类标注数据的情况下，通过不断自我训练在Diplomacy等复杂博弈中实现：",
                    sub1: "超越人类水平的策略规划",
                    sub2: "动态谈判能力与多方对抗"
                },
                work2: {
                    title: "复杂记忆系统架构设计",
                    item1: "调研多种 Agent 长期记忆管理方案，重点探索以下方法：",
                    sub1Html: "Zettelkasten（卢曼卡片盒）思想：基于动态索引与链接构建记忆网络（参考 <a href=\"http://arxiv.org/abs/2502.12110\" target=\"_blank\">A-Mem</a>）",
                    sub2Html: "艾宾浩斯遗忘曲线 + 图数据库：结合 <a href=\"http://arxiv.org/abs/2305.10250\" target=\"_blank\">MemoryBank</a> 和 <a href=\"http://arxiv.org/abs/2504.19413\" target=\"_blank\">Mem0</a>，优化记忆更新机制",
                    item2: "目标：确保 Agent 在长周期博弈中保持上下文一致性，提高决策连贯性"
                }
            }
        },
        projects: {
            title: "项目经历",
            project1: {
                title: "[1] 不良言论识别模型",
                content: "基于 Llama-13B 使用 LoRA 进行轻量微调，设计五维恶意值向量输出并通过雷达图可视化，使用 INT8 量化生成轻量化模型；负责数据集构建、标签体系设计与模型训练。",
                videoBtn: "观看视频"
            },
            project2: {
                title: "[2] \"智体无界 — 基于类脑架构的运动智能体\"（荣获中国国际大学生创新大赛铜奖）",
                content: "基于国家乒乓球运动员数据集，融合图神经网络、时空双流模型实现毫米级动作量化与智能技战术分析；负责动作识别与分割、动作分析逻辑设计与参数优化。",
                videoBtn: "观看视频"
            },
            project3: {
                title: "[3] 配备2D激光雷达的迷宫导航与建图自主移动机器人（团队综合成绩位列年级前十）",
                content: "Design&Build 课程项目，代码：<a href=\"https://github.com/getstronger-sys/Radar-car\" target=\"_blank\" class=\"code-link\">配备2D激光雷达的迷宫导航与建图自主移动机器人</a>。作为项目负责人，独立完成 SLAM 实时建图、DWA 局部避障及 A* 路径规划，合作完成传感器与控制硬件对接。",
                videoBtn: "观看视频"
            },
            project4: {
                title: "[4] 北京地铁查询系统（独立开发）",
                content: "数据结构与算法课程设计，代码：<a href=\"https://github.com/getstronger-sys/Beijing-Metro-Information-Query-System\" target=\"_blank\" class=\"code-link\">北京地铁查询系统</a>。实现基于邻接表+最小堆优化的双策略路径规划，线路级剪枝提升查询效率30%，整合真实时刻表数据实现动态线路管理与实时发车模拟。",
                reportBtn: "查看报告"
            },
            project5: {
                title: "[5] 工程技术学会（IET）颁发的2025年模型国际会议（MIC）最佳海报奖与优秀论文",
                content: "论文\"Technology-Driven Sports Digital Twin: Human-Machine Collaborative Olympic Strategic Decision System\"提出面向奥运会的战略决策框架，结合 K-means 聚类、时间序列预测与马尔可夫模型实现奖牌分布预测与跨国训练优化。",
                posterBtn: "观看海报"
            }
        },
        competitions: {
            title: "竞赛",
            comp1: "2024 全国大学生数学竞赛一等奖",
            comp2: "2025 全国大学生数学建模竞赛国家二等奖",
            comp2WorkBtn: "查看作品",
            comp3: "2024 首届高校ICT产教融合创新大赛二等奖",
            comp4: "2024 全国大学生英语竞赛三等奖"
        },
        skills: {
            title: "专业能力",
            programming: {
                title: "编程语言",
                content: "C/C++、Python、Java<br>SQL、HTML/CSS/JavaScript"
            },
            computer: {
                title: "计算机基础",
                content: "数据结构与算法<br>数据库技术、Git版本管理"
            },
            ai: {
                title: "AI/机器学习",
                content: "GenAI：VAE、GAN、Diffusion<br>CNN/RNN/Transformer<br>PyTorch/TensorFlow框架"
            },
            other: {
                title: "英语能力&其他技能",
                content: "LaTeX、达芬奇剪辑与调色<br><a href=\"images/英语成绩证明/2023213677_四级成绩证明.pdf\" target=\"_blank\" class=\"cert-link\">英语四级</a>、<a href=\"images/英语成绩证明/2023213677_六级成绩证明.pdf\" target=\"_blank\" class=\"cert-link\">英语六级</a>"
            }
        },
        honors: {
            title: "荣誉",
            honor1: "国家奖学金（2023-2024，2024-2025）",
            honor2: "校级三好学生（2023-2024）优秀学生干部（2024-2025）",
            honor3: "北京市三好学生（2025-2026）",
            honor4: "北京邮电大学优秀团员（2023-2024，2024-2025）",
            honor5: "成功入选2024 Winter trip，赴英国交流学习",
            certificates: "获奖证书",
            cert1: "国家奖学金证书",
            cert2: "全国大学生数学竞赛一等奖",
            cert3: "全国大学生数学建模竞赛国家二等奖",
            cert4: "全国大学生英语竞赛三等奖",
            cert5: "IET MIC最佳海报奖与优秀论文",
            cert6: "ICT二等奖",
            cert7: "全国大学生数学建模竞赛国家二等奖",
            cert8: "优秀班集体",
            cert9: "北京市三好学生证书",
            cert10: "国家奖学金证书（2024-2025）"
        },
        others: {
            title: "其他",
            studentWork: {
                title: "学生工作与思想政治：",
                content: "中国共产党预备党员<br>团支部书记和班长，<a href=\"#\" onclick=\"event.preventDefault(); scrollToCertificate('优秀班集体'); return false;\" class=\"cert-link\">多次评选为优秀团支部</a><br>校级学生代表，联署提案并多次参与学生代表大会"
            },
            practice: {
                title: "实践经历：",
                content: "<a href=\"images/实习证明.pdf\" target=\"_blank\" class=\"cert-link\">科大讯飞实习</a>，数学AI模型训练与优化；<a href=\"images/志愿时长.pdf\" target=\"_blank\" class=\"cert-link\">志愿服务时长</a>累计161小时。"
            }
        },
        contact: {
            title: "联系我"
        },
        table: {
            courseName: "课程名称",
            courseType: "课程性质",
            grade: "成绩",
            credits: "学分"
        },
        courses: {
            course1: "计算导论与程序设计课程设计",
            course2: "高等数学A",
            course3: "数据结构",
            course4: "形式语言与自动机",
            course5: "Python程序设计",
            course6: "数字电路设计",
            course7: "数据结构与算法课程设计",
            course8: "Design & Build 实训(智能)",
            course9: "电子系统基础",
            course10: "离散数学",
            course11: "人工智能导论",
            course12: "产品开发与管理",
            course13: "概率论与数理统计",
            course14: "JAVA高级语言程序设计",
            course15: "线性代数",
            course16: "数据库系统",
            course17: "操作系统",
            course18: "机器学习",
            course19: "数据挖掘",
            course20: "嵌入式系统",
            typeRequired: "必修",
            typeElective: "选修"
        }
    },
    en: {
        nav: {
            home: "Home",
            education: "Education",
            publications: "Publications",
            research: "Research",
            projects: "Projects",
            competitions: "Competitions",
            skills: "Skills",
            honors: "Honors",
            others: "Others",
            contact: "Contact"
        },
        home: {
            name: "Weiyi Li",
            research: "Research Interests: LLM & Agent Security / Verifiable Behavior and RL Alignment"
        },
        footer: {
            lastUpdate: "Last Updated"
        },
        modal: {
            selectLanguage: "请选择语言 / Please Select Language"
        },
        education: {
            title: "Education",
            university: "Beijing University of Posts and Telecommunications | Intelligent Science and Technology",
            period: "(2023.09 -- 2027.06)",
            gpa: "GPA: 3.88/4.0 | Weighted Average: 93.44/100",
            rank: "Major Rank: 1/98 (1.0%)",
            courses: "Key Courses"
        },
        publications: {
            title: "Publications",
            zhiwujie: {
                title: "Boundless Intelligence — Brain-Inspired Architecture Sports Agent",
                badge1: "National Innovation Competition",
                badge2: "Bronze Award"
            }
        },
        research: {
            title: "Research Experience",
            lab1: {
                name: "Jianghuai Frontier Technology Collaborative Innovation Center AI Security Professional Department",
                period: "(2025.06 -- Present)",
                position: "Undergraduate Intern | Advisor: Dr. Jiang Fang",
                project1: {
                    title: "[1] Stylistic Idiosyncrasies of Code Generated by Large Language Models (Accepted by CSCWD)",
                    desc1: "Project Description: Addressing the security auditing challenges posed by the widespread adoption of LLM-generated code, this research combines supervised contrastive learning with classification fine-tuning to achieve fine-grained recognition and style feature extraction of code generated by different LLMs through constructing a high-quality multi-model code Q&A dataset. Experimental results show significant model distinguishability with 93.25% accuracy, providing important value for code source identification and auditing.",
                    desc2: "My Contribution: As <strong>first author</strong>, I was responsible for multi-class code generation dataset construction and cleaning; built the LLM2Vec encoder based on Meta-Llama-3-8B, completed supervised contrastive learning and M-class classifier training; extracted and quantified code style features including variable naming, comment usage, and other structured patterns, analyzing model differences; drew research figures and visualized experimental results; completed paper writing and experimental appendix organization."
                },
                project2: {
                    title: "[2] SAT4RIDS: Self-Supervised Learning Adversarial Training Framework for Robust Network Intrusion Detection System (Manuscript prepared)",
                    desc1: "Project Description: Abnormal traffic identification in network intrusion detection has long faced insufficient robustness against adversarial samples. This research proposes a self-supervised + adversarial training network intrusion detection framework that integrates adversarial sample generation into self-supervised learning. The method achieves excellent performance on CICIoT2022 and ISCXVPN2016 datasets, with 99.86% accuracy on original samples and 87.53% on adversarial samples.",
                    desc2: "My Contribution: As <strong>first author</strong>, I was responsible for designing the self-supervised feature learning framework and introducing adversarial training mechanisms to improve model robustness; analyzed and quantified performance differences between original and adversarial samples; completed paper writing and drew research figures to present the model's robustness improvement."
                }
            },
            lab2: {
                name: "BUPT Key Laboratory of Network System Architecture and Convergence",
                period: "(2025.11 -- Present)",
                position: "Undergraduate Intern | Advisor: Prof. Hailun Xia",
                project1: {
                    title: "[1] Signal-SGN++: Topology-Enhanced Time–Frequency Spiking Graph Network for Skeleton-Based Action Recognition (IEEE TNNLS, Under Review)",
                    desc1: "Project Description: Addressing the accuracy and energy consumption challenges of skeleton-based action recognition on resource-constrained devices, this research combines 1D spiking graph convolution with frequency spiking convolution to model the spatial topology, temporal dynamics, and frequency-domain features of skeletal joints simultaneously. Validated on NTU-RGB+D/NTU120/NW-UCLA datasets, Top-1 accuracy improved by 8-15% over baseline, energy consumption reduced by 30% compared to traditional GCN, and FLOPs reduced by 77%-93%.",
                    desc2: "My Contribution: Participated in the technical design and implementation of the MWTF module (Multi-scale Wavelet Transform Fusion) and TSSA module (Topology-Shift Self-Attention); responsible for drawing research figures and method visualization, intuitively presenting complex network structures, experimental procedures, and results."
                }
            },
            lab3: {
                name: "BUPT School of Cyberspace Security – National Engineering Laboratory for Mobile Internet Security Technology",
                period: "(2024.06 -- Present)",
                position: "Undergraduate Intern | Advisor: Prof. Guoshun Nan",
                project1: {
                    title: "[1] When Contrastive Decoding Teaches Time: Annotation-Free RL for Reasoning over Temporal Dynamics (TPAMI, Under Review)",
                    desc1: "Project Description: Addressing the inconsistent causal logic in video temporal modeling by multimodal large models and the high cost of manually constructed annotation signals, this project proposes a framework based on contrastive decoding + GRPO reinforcement learning, enhancing causal signals in forward and reverse-ordered videos to achieve improved causal consistency and temporal sensitivity for dynamic video tasks, achieving SOTA performance without annotations.",
                    desc2: "My Contribution: Responsible for literature review and survey, systematically organizing frontier methods and technical routes in video temporal modeling; collected, cleaned, and integrated multi-source video datasets (RTime-QA, TempCompass, MVBench, TemporalQA); developed inference scripts for different models (VideoLLaVA-7B, MiniCPM-V-2.6-8B, TimeChat) and GPT-3 evaluation scripts. Code is available via <a href=\"https://anonymous.4open.science/r/test-G15b7423-117/README.md\" target=\"_blank\">this link</a>."
                }
            },
            lab4: {
                name: "CAS Institute of Automation – Key Laboratory of Complex System Cognition and Decision",
                period: "(2026.01 -- Present)",
                position: "Undergraduate Intern | Advisor: Prof. Kaiqi Huang",
                direction: "Research Direction: LLM-based Agents for Human-Machine Gaming",
                mainWork: "Main Work and Achievements:",
                work1: {
                    title: "Self-Evolving Game Agent Mechanism Research",
                    item1Html: "Constructing a self-evolving agent framework based on large language models (referencing <a href=\"https://proceedings.neurips.cc/paper_files/paper/2024/hash/df2d62b96a4003203450cf89cd338bb7-Abstract-Conference.html\" target=\"_blank\">Richelieu</a>).",
                    item2: "Researching Self-Play methods to enable agents to achieve, without human-annotated data, through continuous self-training in complex games like Diplomacy:",
                    sub1: "Strategy planning beyond human level",
                    sub2: "Dynamic negotiation capabilities and multi-party competition"
                },
                work2: {
                    title: "Complex Memory System Architecture Design",
                    item1: "Surveying various Agent long-term memory management solutions, focusing on exploring:",
                    sub1Html: "Zettelkasten (Luhmann's card box) approach: Building memory networks through dynamic indexing and linking (referencing <a href=\"http://arxiv.org/abs/2502.12110\" target=\"_blank\">A-Mem</a>)",
                    sub2Html: "Ebbinghaus forgetting curve + graph database: Combining <a href=\"http://arxiv.org/abs/2305.10250\" target=\"_blank\">MemoryBank</a> and <a href=\"http://arxiv.org/abs/2504.19413\" target=\"_blank\">Mem0</a> to optimize memory update mechanisms",
                    item2: "Goal: Ensure Agent maintains context consistency in long-cycle games and improves decision coherence"
                }
            }
        },
        projects: {
            title: "Projects",
            project1: {
                title: "[1] Harmful Speech Detection Model",
                content: "Lightweight fine-tuning of Llama-13B using LoRA, designed five-dimensional malicious value vector output with radar chart visualization, generated lightweight model using INT8 quantization; responsible for dataset construction, label system design, and model training.",
                videoBtn: "Watch Video"
            },
            project2: {
                title: "[2] \"Boundless Intelligence — Brain-Inspired Architecture Sports Agent\" (Bronze Award, China International College Students Innovation Competition)",
                content: "Based on national table tennis athlete dataset, integrated graph neural networks and spatiotemporal dual-stream models to achieve millimeter-level action quantification and intelligent tactical analysis; responsible for action recognition and segmentation, action analysis logic design, and parameter optimization.",
                videoBtn: "Watch Video"
            },
            project3: {
                title: "[3] 2D LiDAR-Based Maze Navigation and Mapping Autonomous Mobile Robot (Team ranked top 10 in grade)",
                content: "Design&Build course project, code: <a href=\"https://github.com/getstronger-sys/Radar-car\" target=\"_blank\" class=\"code-link\">2D LiDAR-Based Maze Navigation and Mapping Autonomous Mobile Robot</a>. As project leader, independently completed SLAM real-time mapping, DWA local obstacle avoidance, and A* path planning, collaborated on sensor and control hardware integration.",
                videoBtn: "Watch Video"
            },
            project4: {
                title: "[4] Beijing Metro Query System (Independent Development)",
                content: "Data Structures and Algorithms course design, code: <a href=\"https://github.com/getstronger-sys/Beijing-Metro-Information-Query-System\" target=\"_blank\" class=\"code-link\">Beijing Metro Query System</a>. Implemented dual-strategy path planning based on adjacency list + min-heap optimization, improved query efficiency by 30% through route-level pruning, integrated real-time schedule data for dynamic route management and real-time departure simulation.",
                reportBtn: "View Report"
            },
            project5: {
                title: "[5] IET MIC 2025 Best Poster Award and Excellent Paper",
                content: "Paper \"Technology-Driven Sports Digital Twin: Human-Machine Collaborative Olympic Strategic Decision System\" proposes an Olympic-oriented strategic decision framework, combining K-means clustering, time series prediction, and Markov models to achieve medal distribution prediction and cross-national training optimization.",
                posterBtn: "View Poster"
            }
        },
        competitions: {
            title: "Competitions",
            comp1: "2024 National College Students Mathematics Competition First Prize",
            comp2: "2025 National College Students Mathematical Modeling Competition National Second Prize",
            comp2WorkBtn: "View Work",
            comp3: "2024 First University ICT Industry-Education Integration Innovation Competition Second Prize",
            comp4: "2024 National College Students English Competition Third Prize"
        },
        skills: {
            title: "Skills",
            programming: {
                title: "Programming Languages",
                content: "C/C++, Python, Java<br>SQL, HTML/CSS/JavaScript"
            },
            computer: {
                title: "Computer Fundamentals",
                content: "Data Structures & Algorithms<br>Database Technology, Git Version Control"
            },
            ai: {
                title: "AI/Machine Learning",
                content: "GenAI: VAE, GAN, Diffusion Models<br>CNN/RNN/Transformer<br>PyTorch/TensorFlow Frameworks"
            },
            other: {
                title: "English Proficiency & Other Skills",
                content: "LaTeX, DaVinci Editing & Color Grading<br><a href=\"images/英语成绩证明/2023213677_四级成绩证明.pdf\" target=\"_blank\" class=\"cert-link\">CET-4</a>, <a href=\"images/英语成绩证明/2023213677_六级成绩证明.pdf\" target=\"_blank\" class=\"cert-link\">CET-6</a>"
            }
        },
        honors: {
            title: "Honors",
            honor1: "National Scholarship (2023-2024, 2024-2025)",
            honor2: "University Outstanding Student (2023-2024) Outstanding Student Cadre (2024-2025)",
            honor3: "Beijing Outstanding Student (2025-2026)",
            honor4: "BUPT Outstanding League Member (2023-2024, 2024-2025)",
            honor5: "Selected for 2024 Winter trip, exchange study in UK",
            certificates: "Awards & Certificates",
            cert1: "National Scholarship Certificate",
            cert2: "National College Students Mathematics Competition First Prize",
            cert3: "National College Students Mathematical Modeling Competition National Second Prize",
            cert4: "National College Students English Competition Third Prize",
            cert5: "IET MIC Best Poster Award and Excellent Paper",
            cert6: "ICT Second Prize",
            cert7: "National College Students Mathematical Modeling Competition National Second Prize",
            cert8: "Outstanding Class Collective",
            cert9: "Beijing Outstanding Student Certificate",
            cert10: "National Scholarship Certificate (2024-2025)"
        },
        others: {
            title: "Others",
            studentWork: {
                title: "Student Work & Ideological-Political:",
                content: "Probationary member of the Communist Party of China<br>Secretary and class monitor of the Youth League branch, <a href=\"#\" onclick=\"event.preventDefault(); scrollToCertificate('优秀班集体'); return false;\" class=\"cert-link\">repeatedly selected as an excellent Youth League branch</a><br>School-level student representative, co-signed proposals and participated in student representative meetings multiple times"
            },
            practice: {
                title: "Practical Experience:",
                content: "<a href=\"images/实习证明.pdf\" target=\"_blank\" class=\"cert-link\">iFlytek internship</a>, mathematical AI model training and optimization; cumulative <a href=\"images/志愿时长.pdf\" target=\"_blank\" class=\"cert-link\">volunteer service hours</a>: 161 hours."
            }
        },
        contact: {
            title: "Contact Me"
        },
        table: {
            courseName: "Course Name",
            courseType: "Course Type",
            grade: "Grade",
            credits: "Credits"
        },
        courses: {
            course1: "Introduction to Computing and Programming Course Design",
            course2: "Advanced Mathematics A",
            course3: "Data Structures",
            course4: "Formal Languages and Automata",
            course5: "Python Programming",
            course6: "Digital Circuit Design",
            course7: "Data Structures and Algorithms Course Design",
            course8: "Design & Build Training (Intelligent)",
            course9: "Fundamentals of Electronic Systems",
            course10: "Discrete Mathematics",
            course11: "Introduction to Artificial Intelligence",
            course12: "Product Development and Management",
            course13: "Probability Theory and Mathematical Statistics",
            course14: "JAVA Advanced Language Programming",
            course15: "Linear Algebra",
            course16: "Database Systems",
            course17: "Operating Systems",
            course18: "Machine Learning",
            course19: "Data Mining",
            course20: "Embedded Systems",
            typeRequired: "Required",
            typeElective: "Elective"
        }
    }
};

// 当前语言
let currentLang = localStorage.getItem('language') || 'en';

// 翻译函数
function translate(key) {
    const keys = key.split('.');
    let value = translations[currentLang];
    for (const k of keys) {
        value = value?.[k];
    }
    return value || key;
}

// 更新页面语言
function updateLanguage(lang) {
    currentLang = lang;
    localStorage.setItem('language', lang);
    
    // 更新所有带data-i18n属性的元素
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        const text = translate(key);
        if (text) {
            // 如果包含HTML标签（如<br>, <a>, <strong>, <em>），使用innerHTML，否则使用textContent
            if (text.includes('<') && text.includes('>')) {
                element.innerHTML = text;
            } else {
                element.textContent = text;
            }
        }
    });
    
    // 更新语言切换按钮
    const currentLangSpan = document.getElementById('currentLang');
    const targetLangSpan = document.getElementById('targetLang');
    if (lang === 'zh') {
        currentLangSpan.textContent = '中文';
        targetLangSpan.textContent = 'EN';
    } else {
        currentLangSpan.textContent = 'EN';
        targetLangSpan.textContent = '中文';
    }
    
    // 更新HTML lang属性
    document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
}

// 切换语言
function toggleLanguage() {
    const newLang = currentLang === 'zh' ? 'en' : 'zh';
    updateLanguage(newLang);
}

// 选择语言并关闭模态框
function selectLanguage(lang) {
    updateLanguage(lang);
    closeLanguageModal();
}

// 关闭语言选择模态框
function closeLanguageModal() {
    const modal = document.getElementById('languageModal');
    if (modal) {
        modal.classList.remove('show');
        localStorage.setItem('languageSelected', 'true');
    }
}

// 页面加载时应用保存的语言
document.addEventListener('DOMContentLoaded', () => {
    // 检查是否已经选择过语言
    const languageSelected = localStorage.getItem('languageSelected');
    
    // 如果没有选择过语言，显示语言选择提示框
    if (!languageSelected) {
        const modal = document.getElementById('languageModal');
        if (modal) {
            modal.classList.add('show');
        }
    } else {
        // 如果已经选择过，直接应用保存的语言
        updateLanguage(currentLang);
    }
    
    // 绑定语言切换按钮
    const langToggle = document.getElementById('langToggle');
    if (langToggle) {
        langToggle.addEventListener('click', toggleLanguage);
    }
});
